[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pdfplumber>=0.11.5",
    "pdfrw>=0.4",
    "reportlab>=4.3.0",
]
